blog/urls.py
from django.urls import path

from . import views
from .views import PostListView, UserPublicProfile

app_name = 'blog'
urlpatterns = [
    path('post/', PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', views.post_detail, name='post-detail'),
    path('post/create/', views.post_creation, name='post-create'),
    path('post/user/', views.post_user_list, name='user-post-list'),
    path('post/contact/', views.contact, name='contact'),

    path('profile/<int:pk>', UserPublicProfile.as_view(), name='user-public-profile'),
]

blog/models.py
from django.contrib.auth.models import User
from django.db import models


class Post(models.Model):
    headline = models.CharField(max_length=255)
    short_description = models.CharField(max_length=255)
    description = models.TextField()
    image = models.ImageField(upload_to='images')
    blank = models.BooleanField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.headline


class Comment(models.Model):
    username = models.CharField(max_length=255, default="Anonymous")
    text = models.TextField()
    is_published = models.BooleanField(default=False)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return self.username

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm

from .models import Comment, Post


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ["headline", "short_description", "description", "image", "blank"]


class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ["text"]


class ContactForm(forms.Form):
    email = forms.EmailField(required=True)
    subject = forms.CharField(required=True)
    text = forms.CharField(required=True, widget=forms.Textarea)

blog/views.py
from blog.forms import RegisterForm

from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.messages.views import SuccessMessageMixin
from django.core.paginator import Paginator
from django.http import JsonResponse
from django.shortcuts import redirect, render
from django.template.loader import render_to_string
from django.urls import reverse, reverse_lazy
from django.views.generic.detail import DetailView
from django.views.generic.edit import FormView, UpdateView
from django.views.generic.list import ListView

from .forms import CommentForm, ContactForm, PostForm
from .models import Post
from .tasks import send_email as celery_send_email


class RegisterFormView(FormView):
    template_name = "registration/register.html"
    form_class = RegisterForm
    success_url = reverse_lazy('profile')

    def form_valid(self, form):
        user = form.save()

        login(self.request, user)
        return super(RegisterFormView, self).form_valid(form)


class UpdateProfile(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    fields = ["first_name", "last_name", "email"]
    template_name = "registration/update_profile.html"
    success_url = reverse_lazy('profile')
    success_message = "Profile was updated successfully"

    def get_object(self, queryset=None):
        user = self.request.user
        return user


class UserProfile(LoginRequiredMixin, DetailView):
    model = User
    template_name = "registration/profile.html"

    def get_object(self, queryset=None):
        user = self.request.user
        return user

    def get_context_data(self, **kwargs):
        context = super(UserProfile, self).get_context_data(**kwargs)
        context['posts_count'] = self.get_object().post_set.count()
        return context


class UserPublicProfile(DetailView):
    model = User
    template_name = 'blog/public_profile.html'


@login_required
def post_creation(request):
    if request.method == "POST":
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form = form.save(commit=False)
            form.user = request.user
            form.save()
            celery_send_email.delay(
                'Action',
                'New post was added',
                'noreply@example.com',
                ['admin@mail.com']
            )
            messages.add_message(request, messages.SUCCESS, 'Post was successfully created')
            return redirect('blog:post-list')
    else:
        form = PostForm()

    return render(
        request,
        'blog/post_create_form.html',
        context={
            "form": form,
        }
    )


class PostListView(ListView):
    model = Post
    paginate_by = 10

    def get_queryset(self):
        return Post.objects.filter(blank=False)


def post_detail(request, pk):
    post_instance = Post.objects.prefetch_related('comment_set').get(pk=pk)

    comment_list = post_instance.comment_set.all()
    paginator = Paginator(comment_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.post = Post.objects.get(pk=pk)
            if request.user.is_authenticated:
                form.username = request.user.username
            form.save()
            celery_send_email.delay(
                'Action',
                'New comment was added',
                'noreply@example.com',
                'admin@mail.com'
            )
            link = reverse('blog:post-detail', kwargs={"pk": pk})
            celery_send_email.delay(
                'Action',
                f'New comment was added {link}',
                'noreply@example.com',
                post_instance.user.email
            )
            return redirect('blog:post-list')
    else:
        form = CommentForm()

    return render(
        request,
        'blog/post_detail.html',
        context={
            "form": form,
            "post_instance": post_instance,
            'page_obj': page_obj,
        }
    )


@login_required
def post_user_list(request):
    post_list = Post.objects.filter(user=request.user)

    paginator = Paginator(post_list, 10)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    return render(
        request,
        'blog/post_user_list.html',
        context={
            'post_list': post_list,
            'page_obj': page_obj,
        }
    )


# def contact(request):
#     if request.method == "POST":
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             email = form.cleaned_data['email']
#             subject = form.cleaned_data['subject']
#             text = form.cleaned_data['text']
#             celery_send_email.delay(
#                 subject,
#                 text,
#                 email,
#                 'admin@mail.com'
#             )
#             messages.add_message(request, messages.SUCCESS, 'Message sent')
#             return redirect('blog:post-list')
#     else:
#         form = ContactForm()
#     return render(
#         request,
#         'blog/contact.html',
#         context={
#             'form': form,
#         }
#     )

# Modal
def contact(request):
    data = dict()
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            subject = form.cleaned_data['subject']
            text = form.cleaned_data['text']
            celery_send_email.delay(
                subject,
                text,
                email,
                'admin@mail.com'
            )
            data['form_is_valid'] = True
            data['html_successmessage'] = render_to_string('blog/includes/partial_successmessage.html')
        else:
            data['form_is_valid'] = False
    else:
        form = ContactForm()
    context = {'form': form}
    data['html_form'] = render_to_string('blog/includes/partial_contact.html', context, request=request)
    return JsonResponse(data)

templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Title{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
        integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"
          integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV"
          crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.bundle.min.js"
          integrity="sha384-LtrjvnR4Twt/qOuYxE721u19sVFLVSA4hf/rRt6PrZTmiPltdZcI7q7PXQBYTKyf"
          crossorigin="anonymous"></script>
    {% block extra_css %}
    {% endblock %}
    {% block extra_js %}
        <script src="{% static 'js/blog.js' %}"></script>
    {% endblock %}
</head>
<body>

{% if messages %}
<ul class="messages" align="center" style="background-color: chartreuse">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>
        {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Important: {% endif %}
        {{ message }}
    </li>
    {% endfor %}
</ul>
{% endif %}

{% block content %}{% endblock %}

<div class="modal fade" id="modal-contactform">
    <div class="modal-dialog">
      <div class="modal-content">

      </div>
    </div>
</div>

</body>
</html>

templates/blog/contact.html
{% extends 'blog/base.html' %}

{% block title %}Contact us{% endblock %}

{% block content %}

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Send">
    </form>

{% endblock %}

templates/blog/post_create_form.html
{% extends 'blog/base.html' %}

{% block title %}Create post{% endblock %}

{% block content %}

    <p>
        <button type="button" class="btn btn-primary js-contact" data-url="{% url 'blog:contact' %}">
        <span class="glyphicon glyphicon-plus"></span>
            Contact us!
        </button>
    </p>

    <form enctype="multipart/form-data" method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Save">
    </form>

{% endblock %}

templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block title %}Post detail{% endblock %}

{% block content %}

    <p>
        <button type="button" class="btn btn-primary js-contact" data-url="{% url 'blog:contact' %}">
        <span class="glyphicon glyphicon-plus"></span>
            Contact us!
        </button>
    </p>

    <table>
        <tr>
            <th>Headline</th>
            <th>Short description</th>
            <th>Description</th>
            <th>Image</th>
            <th>User</th>
        </tr>
        <tr>
            <th>{{ post_instance.headline }}</th>
            <th>{{ post_instance.short_description }}</th>
            <th>{{ post_instance.description }}</th>
            <th>{{ post_instance.image }}</th>
            <th><a href="{% url 'blog:user-public-profile' pk=post_instance.user.pk %}">{{ post_instance.user }}</a></th>
        </tr>
    </table>

    <ul>
        {% for comment in post_instance.comment_set.all %}
            {% if comment.is_published == True %}
                <li>Username:{{ comment.username }} || Comment: {{ comment.text }} </li>
            {% endif %}
        {% endfor %}
    </ul>

    <div class="pagination">
        {% if is_paginated %}
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        {% endif %}
    </div>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
    <input type="submit" value="Publish">
    </form>

{% endblock %}

templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block title %}List of posts{% endblock %}

{% block content %}

{#    <p>Any problems? <a href="{% url 'blog:contact' %}">Contact us!</a></p>#}

    <p>
        <button type="button" class="btn btn-primary js-contact" data-url="{% url 'blog:contact' %}">
        <span class="glyphicon glyphicon-plus"></span>
            Contact us!
        </button>
    </p>

    <table>
        <tr>
            <th>Headline</th>
            <th>Short description</th>
            <th>Description</th>
            <th>Image</th>
        </tr>
    {% for post in object_list %}
        <tr>
            <th><a href="{% url 'blog:post-detail' pk=post.pk %}">{{ post.headline }}</a></th>
            <th>{{ post.short_description }}</th>
            <th>{{ post.description }}</th>
            <th>{{ post.image }}</th>
        </tr>
    {% empty %}
        <tr>
            <th>None</th>
            <th>None</th>
            <th>None</th>
            <th>None</th>
        </tr>
    {% endfor %}
    </table>

    <div class="pagination">
        {% if is_paginated %}
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        {% endif %}
    </div>

{% endblock %}

templates/blog/post_user_list.html
{% extends 'blog/base.html' %}

{% block title %}User's posts list{% endblock %}

{% block content %}

    <p>
        <button type="button" class="btn btn-primary js-contact" data-url="{% url 'blog:contact' %}">
        <span class="glyphicon glyphicon-plus"></span>
            Contact us!
        </button>
    </p>

    <table>
        <tr>
            <th>Headline</th>
            <th>Short description</th>
            <th>Description</th>
            <th>Image</th>
        </tr>
    {% for post in post_list %}
        <tr>
            <th><a href="{% url 'blog:post-detail' pk=post.pk %}">{{ post.headline }}</a></th>
            <th>{{ post.short_description }}</th>
            <th>{{ post.description }}</th>
            <th>{{ post.image }}</th>
        </tr>
    {% empty %}
        <tr>
            <th>None</th>
            <th>None</th>
            <th>None</th>
            <th>None</th>
        </tr>
    {% endfor %}
    </table>

    <div class="pagination">
        {% if is_paginated %}
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1">&laquo; first</a>
                    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
                </span>

                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">next</a>
                    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        {% endif %}
    </div>

{% endblock %}

templates/blog/public_profile.html
{% extends "blog/base.html" %}

{% block title %}User profile{% endblock %}

{% block content %}

    <p>
        <button type="button" class="btn btn-primary js-contact" data-url="{% url 'blog:contact' %}">
        <span class="glyphicon glyphicon-plus"></span>
            Contact us!
        </button>
    </p>

    <p>{{ object.username }}</p>
    <p>{{ object.email }}</p>

{% endblock %}